transactions_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PLATFORM_DB_HOST', 'postgres') }}"
      port: 5432
      dbname: "{{ env_var('PLATFORM_DB_NAME') }}"
      user: "{{ env_var('PLATFORM_DB_USER') }}"
      password: "{{ env_var('PLATFORM_DB_PASSWORD') }}"
      schema: transformed
      threads: 4